### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by ManyiLee** [Leminhbinh0209/ICCV23-QAD#1]
Does it has a preprocess code for generating json file ? And the data quality distribution.

**Comment by Leminhbinh0209** [comment]
Hi,

You can create it upon your available data. If you have three quality modalities (raw-c23-c40), then it should be 3 lists+label list, for train-val-test like my example JSON file:

```
{
"train":{
	"raw": ["train_img1_raw.png", "train_img2_raw.png", "train_img2_raw.png"],
	"c23": ["train_img1_c23.png", "train_img2_c23.png", "train_img2_c23.png"],
	"c40": ["train_img1_c40.png", "train_img2_c40.png", "train_img2_c40.png"],
	"labels": ["<label_train_img1>", "<label_train_img2>", "<label_train_img3>"]
},
"val": {
	"raw": ["val_img1_raw.png", "val_img2_raw.png"],
	"c23": ["val_img1_c23.png", "val_img2_c23.png"],
	"c40": ["val_img1_c40.png", "val_img2_c40.png"],
	"labels": ["<label_val_img1>", "<label_val_img2>"]
},
"test": {
	"raw": ["test_img1_raw.png", "test_img2_raw.png"],
	"c23": ["test_img1_c23.png", "test_img2_c23.png"],
	"c40": ["test_img1_c40.png", "test_img2_c40.png"],
	"labels": ["<label_test_img1>", "<label_test_img2>"]
}
}```

**Comment by ManyiLee** [comment]
ok, I get it now, thanks!




string1313
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Leminhbinh0209/ICCV23-QAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月2日(星期六) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Leminhbinh0209/ICCV23-QAD] preprocess (Issue #1)





 
Hi,
 
You can create it upon your available data. If you have three quality modalities (raw-c23-c40), then it should be triplet for train-val-test like my example JSON file:
 { "train":{ 	"raw": ["train_img1_raw.png", "train_img2_raw.png", "train_img2_raw.png"], 	"c23": ["train_img1_c23.png", "train_img2_c23.png", "train_img2_c23.png"], 	"c40": ["train_img1_c40.png", "train_img2_c40.png", "train_img2_c40.png"], 	"labels": ["<label_train_img1&gt;", "<label_train_img2&gt;", "<label_train_img3&gt;"] }, "val": { 	"raw": ["val_img1_raw.png", "val_img2_raw.png"], 	"c23": ["val_img1_c23.png", "val_img2_c23.png"], 	"c40": ["val_img1_c40.png", "val_img2_c40.png"], 	"labels": ["<label_val_img1&gt;", "<label_val_img2&gt;"] }, "test": { 	"raw": ["test_img1_raw.png", "test_img2_raw.png"], 	"c23": ["test_img1_c23.png", "test_img2_c23.png"], 	"c40": ["test_img1_c40.png", "test_img2_c40.png"], 	"labels": ["<label_test_img1&gt;", "<label_test_img2&gt;"] } }```
